name: Unit

on:
  workflow_call:
    inputs:
      test-command:
        required: true
        type: string
      fail-fast:
        required: false
        type: boolean
        default: true
      test-timeout:
        required: false
        type: number
        default: 15
      download-binaries:
        required: false
        type: boolean
        default: false
  push:
    branches:
      - 'master'
      - '2.*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'
      - 'psalm-baseline.xml'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'
      - 'psalm-baseline.xml'
      - '.editorconfig'

jobs:
  test:
    name: PHP${{ matrix.php }}${{ matrix.extensions-suffix }}, ${{ matrix.os }}, ${{ matrix.dependencies }} deps
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ inputs.test-timeout }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        os: [ ubuntu-latest ]
        extensions-suffix: [ '', ', protobuf' ]
        dependencies: [ lowest , highest ]
        include:
          - os: windows-latest
            extensions-suffix: ', protobuf'
            php: 8.1
            dependencies: highest
    steps:
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: dom, sockets, grpc, curl ${{ matrix.extensions-suffix }}
#          extensions: dom, sockets, grpc, curl

      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Download CPX (PHP 8.4)
        if: inputs.download-binaries == true && matrix.php == '8.4'
        run: composer global require cpx/cpx

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-${{ matrix.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php-${{ matrix.php }}-${{ matrix.os }}-composer-

      - name: Install lowest dependencies from composer.json
        if: matrix.dependencies == 'lowest' && matrix.php != '8.4'
        run: composer update --no-interaction --no-progress --prefer-lowest

      - name: Install lowest dependencies from composer.json ignoring ext-php constraint (PHP 8.4)
        if: matrix.dependencies == 'lowest' && matrix.php == '8.4'
        run: composer update --no-interaction --no-progress --prefer-lowest --ignore-platform-req php


      - name: Validate lowest dependencies
        if: matrix.dependencies == 'lowest' && matrix.php == '8.1'
        env:
          COMPOSER_POOL_OPTIMIZER: 0
        run: vendor/bin/validate-prefer-lowest


      - name: Install highest dependencies from composer.json
        if: matrix.dependencies == 'highest' && matrix.php != '8.4'
        run: composer update --no-interaction --no-progress

      - name: Install highest dependencies from composer.json ignoring ext-php constraint (PHP 8.4)
        if: matrix.dependencies == 'highest' && matrix.php == '8.4'
        run: composer update --no-interaction --no-progress --ignore-platform-req php


      - name: Download binaries
        if: inputs.download-binaries == true && matrix.php != '8.4'
        run: composer get:binaries

      - name: Download binaries (PHP 8.4)
        if: inputs.download-binaries == true && matrix.php == '8.4'
        run: cpx internal/dload get --no-interaction

      - name: Run tests
        run: ${{ inputs.test-command }}
