name: Static Analysis

on: [push, pull_request]

concurrency:
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}
  group: tests-${{ github.workflow }}-${{ github.ref }}

jobs:
  psalm:
    name: Psalm Validation (PHP ${{ matrix.php }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        os: [ubuntu-latest]
    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: 🔍 Run Tests
        run: vendor/bin/psalm

  arch:
    name: Architecture tests
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        os: [ubuntu-latest]
    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom

      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: 🔍 Run Tests
        run: composer test:arch
